config/routes.rb
Rails.application.routes.draw do
  root 'summaries#new'
  resources :summaries, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create] # dangerous for production

  def new
  end

  def create
    terms = params[:terms]
    summary = generate_summary(terms)
    render plain: summary
  end

  private

  def generate_summary(terms)
    client = OpenAI::Client.new
    response = client.chat(
    parameters: {
        model: "gpt-3.5-turbo", # Required.
        messages: [{ role: "user", prompt: "You are a legal expert specializing in Terms & Conditions and contract law.", content: "Succintly summarize these terms and conditions 
and highlight important points, specifically personal data use or sneaky tactics: 
#{terms}"}], # Required.
        temperature: 0.7,
    })
    puts response.dig("choices", 0, "message", "content")
    return response.dig("choices", 0, "message", "content")
    # response['choices'][0]['text'].strip
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= csrf_meta_tags %>
<html>
  <head>
    <title>TermsSummarizer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/summaries/create.html.erb
<h1>Summaries#create</h1>
<p>Find me in app/views/summaries/create.html.erb</p>

app/views/summaries/new.html.erb
<h1>Summarize Terms and Conditions</h1>
<%= form_with url: summaries_path, method: :post do %>
  <div>
    <%= label_tag :terms, "Terms and Conditions" %><br>
    <%= text_area_tag :terms, nil, rows: 20, cols: 100 %>
  </div>
  <div>
    <%= submit_tag "Summarize" %>
  </div>
<% end %>